/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/threed/low-poly-f1-car.glb --transform 
Files: ./src/assets/threed/low-poly-f1-car.glb [897.22KB] > /home/matthun/dev/noon/low-poly-f1-car-transformed.glb [48.8KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/low-poly-f1-car-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.PaletteMaterial001} position={[-1.843, 1.745, 0]} scale={[0.257, 0.027, 1.507]} />
      <group position={[5.697, 2.828, 0]} scale={[0.371, 0.018, 0.961]}>
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials.PaletteMaterial003} />
      </group>
      <group position={[-1.221, 2.314, -0.037]} rotation={[0, Math.PI / 2, 0]} scale={[0.09, 0.09, 0.031]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.PaletteMaterial005} />
      </group>
    </group>
  )
}

useGLTF.preload('/low-poly-f1-car-transformed.glb')
